[pytest]
testpaths =
    tests
addopts = -ra
filterwarnings =
    ignore:Jupyter is migrating its paths to use standard platformdirs:DeprecationWarning
markers =
    integration: Slurm-based end-to-end integration tests
